name: .NET

on:
  push:
    branches: [ 'master', 'development' ]

defaults:
  run:
    working-directory: Ixian-Seeder

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout Ixian-Seeder
      uses: actions/checkout@v2
      with:
        path: Ixian-Seeder

    - name: Checkout Ixian-Core
      uses: actions/checkout@v2
      with:
        repository: ProjectIxian/Ixian-Core
        path: Ixian-Core
        ref: ${{ github.event.push.ref }}

    # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@2008f912f56e61277eefaac6d1888b750582aa16
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'

    - name: Restore dependencies
      run: nuget restore IxianSeeder.sln

    - name: Building Ixian-Seeder
      run: msbuild IxianSeeder.sln

    #- name: Running Unit Tests
    #  run: dotnet test UnitTests\bin\Debug\unittests.dll --verbosity normal
